language: node_js
node_js:
  - "7"
  - "8"
before_install:
- sudo apt-get install google-chrome-stable
install:
  - npm install
script:
  - npm run test
after_success:
- cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
- rm -rf ./coverage
branches:
  only:
    - master
    - production
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "7"
      script: npm run build
      before_deploy:
        - rm -rf ./src ./test ./coverage ./script
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
          branch: production